apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-orchestrator
  namespace: redis-multisite-b
  labels:
    app: redis-orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-orchestrator
  namespace: redis-multisite-b
  labels:
    app: redis-orchestrator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-orchestrator
  namespace: redis-multisite-b
  labels:
    app: redis-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-orchestrator
subjects:
- kind: ServiceAccount
  name: redis-orchestrator
  namespace: redis-multisite-b

